# Generated by Django 5.2 on 2025-04-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
