# Generated by Django 5.1.7 on 2025-05-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_lesson_lab_description_alter_lesson_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
